export const countryTranslations: any = {
  'Deutschland': 'Germany',
  'Italien': 'Italy',
  'Frankreich': 'France',
  'Spanien': 'Spain',
  'Portugal': 'Portugal',
  'Griechenland': 'Greece',
  'Norwegen': 'Norway',
  'Schweden': 'Sweden',
  'Dänemark': 'Denmark',
  'Finnland': 'Finland',
  'Niederlande': 'Netherlands',
  'Belgien': 'Belgium',
  'Österreich': 'Austria',
  'Schweiz': 'Switzerland',
  'Polen': 'Poland',
  'Tschechien': 'Czech Republic',
  'Kroatien': 'Croatia',
  'Ungarn': 'Hungary',
  'Irland': 'Ireland',
  'Vereinigtes Königreich': 'United Kingdom',
  'Island': 'Iceland',
  'Türkei': 'Turkey',
  'Amerika' : 'United States of America',
  'USA': 'United States of America',
  'Thailand': 'Thailand',
  'Japan': 'Japan',
  'Russland' : 'Russia',
};

export const countryContinents: any = {
  'Germany': 'Europa',
  'Italy': 'Europa',
  'France': 'Europa',
  'Spain': 'Europa',
  'Portugal': 'Europa',
  'Greece': 'Europa',
  'Norway': 'Europa',
  'Sweden': 'Europa',
  'Denmark': 'Europa',
  'Finland': 'Europa',
  'Netherlands': 'Europa',
  'Belgium': 'Europa',
  'Austria': 'Europa',
  'Switzerland': 'Europa',
  'Poland': 'Europa',
  'Czech Republic': 'Europa',
  'Croatia': 'Europa',
  'Hungary': 'Europa',
  'Ireland': 'Europa',
  'United Kingdom': 'Europa',
  'Iceland': 'Europa',
  'Turkey': 'Asien',
  'United States of America': 'Nordamerika',
  'Thailand': 'Asien',
  'Japan': 'Asien',
  'Russia': 'Europa',
};